export interface Api {
  HTTP_STATUS_OK: number;
  HTTP_STATUS_PROCESSING: number;

  HTTP_ERROR_BAD_REQUEST: number;
  HTTP_ERROR_NOT_FOUND: number;
  HTTP_ERROR_INTERNEL_SERVER: number;

  Q_RESET: number;
  Q_REMAINING: number;
  Q_NEXT: number;
  Q_ENTRIES: number;
  Q_ENTRY: number;

  E_UNKNOWN_REQUEST: number;
  E_EMPTY: number;
  E_FILE_SYSTEM: number;
  E_MISSING_UNIQUE_ATTRIBUTE: number;

  R_QUERY_SUCCESS: number;
  R_QUERY_FAILURE: number;
  R_ADD_SUCCESS: number;
  R_ADD_FAILURE: number;
  R_UPDATE_SUCCESS: number;
  R_UPDATE_FAILURE: number;
  R_DELETE_SUCCESS: number;
  R_DELETE_FAILURE: number;
}

const obj: Api = {
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_PROCESSING: 102,

  HTTP_ERROR_BAD_REQUEST: 400,
  HTTP_ERROR_NOT_FOUND: 404,
  HTTP_ERROR_INTERNEL_SERVER: 500,

  Q_RESET: 1050,
  Q_REMAINING: 1051,
  Q_NEXT: 1052,
  Q_ENTRIES: 1053,
  Q_ENTRY: 1054,

  E_UNKNOWN_REQUEST: (-1100),
  E_EMPTY: (-1101),
  E_FILE_SYSTEM: (-1102),
  E_MISSING_UNIQUE_ATTRIBUTE: (-1103),

  R_QUERY_SUCCESS: 1200,
  R_QUERY_FAILURE: (-1200),
  R_ADD_SUCCESS: 1201,
  R_ADD_FAILURE: (-1201),
  R_UPDATE_SUCCESS: 1202,
  R_UPDATE_FAILURE: (-1202),
  R_DELETE_SUCCESS: 1203,
  R_DELETE_FAILURE: (-1203)
};

export const api = obj;
